# $Id: Makefile,v 1.1 1999/06/09 14:14:16 ylo Exp $
# $Log: Makefile,v $
# Revision 1.1  1999/06/09 14:14:16  ylo
# Initial revision
#
#

include $(ROOTDIR)/config.mak
include $(CONFDIR)/stdrules.mak
