// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p10 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be\be_codegen.cpp:487

#ifndef _TAO_IDL_G__BIN_P530_SRC_IMG_IDL_INPUTMGR_SKEL_H_
#define _TAO_IDL_G__BIN_P530_SRC_IMG_IDL_INPUTMGR_SKEL_H_


#include "inputmgr.hh"
#include "scsredtype_skel.hh"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/interface_sh.cpp:87

class POA_InputMgrIdl;
typedef POA_InputMgrIdl *POA_InputMgrIdl_ptr;

class _TAO_InputMgrIdl_Direct_Proxy_Impl;
class _TAO_InputMgrIdl_Strategized_Proxy_Broker;

class  POA_InputMgrIdl
  : public virtual POA_ScsProcessIdl
{
protected:
  POA_InputMgrIdl (void);

public:
  // Useful for template programming.
  typedef ::InputMgrIdl _stub_type;
  typedef ::InputMgrIdl_ptr _stub_ptr_type;
  typedef ::InputMgrIdl_var _stub_var_type;
  
  POA_InputMgrIdl (const POA_InputMgrIdl& rhs);
  virtual ~POA_InputMgrIdl (void);
  
  virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
  
  static void _is_a_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _non_existent_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _interface_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _component_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _repository_id_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant);
  
  virtual void _dispatch (
      TAO_ServerRequest & req,
      void * servant_upcall);
  
  ::InputMgrIdl *_this (void);
  
  virtual const char* _interface_repository_id (void) const;
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual ::ScsStatusIdl InputMgr_failOver (
      void) = 0;
  
  static void InputMgr_failOver_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual ::ScsStatusIdl InputMgr_switchOver (
      void) = 0;
  
  static void InputMgr_switchOver_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual ::ScsStatusIdl readSnapshot (
      void) = 0;
  
  static void readSnapshot_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void standbyEnvironmentUp (
      void) = 0;
  
  static void standbyEnvironmentUp_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void updateTime (
      ::ScsProcessIdl_ptr source,
      ::ScsProcessIdl_ptr destination,
      const ::ScsMessageTag & tag,
      const ::ScsTimeValIdl & onlineTime) = 0;
  
  static void updateTime_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void printMsgOn (
      const char * tty) = 0;
  
  static void printMsgOn_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual void printMsgOff (
      void) = 0;
  
  static void printMsgOff_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_sh.cpp:45
  
  virtual ::ScsStatusIdl dump (
      ::ImgListLengthList_out valueList,
      ::CORBA::Boolean showContents) = 0;
  
  static void dump_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2044
  
  static void
  scs_implementation_skel (
      TAO_ServerRequest & server_request, 
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2044
  
  static void
  scs_host_skel (
      TAO_ServerRequest & server_request, 
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2044
  
  static void
  isAlive_skel (
      TAO_ServerRequest & server_request, 
      void * servant_upcall,
      void * servant
    );
};

///////////////////////////////////////////////////////////////////////
//               Strategized Proxy Broker Declaration 
//

// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/strategized_proxy_broker_sh.cpp:36

class  _TAO_InputMgrIdl_Strategized_Proxy_Broker
  : public virtual TAO::Collocation_Proxy_Broker
{
public: 
  virtual ~_TAO_InputMgrIdl_Strategized_Proxy_Broker (void);
  
  TAO::Collocation_Strategy get_strategy (::CORBA::Object_ptr obj);
  
  void
  dispatch (
      ::CORBA::Object_ptr obj,
      ::CORBA::Object_out forward_obj,
      bool &is_forwarded,
      TAO::Argument ** args,
      int num_args,
      const char * op,
      size_t op_len,
      TAO::Collocation_Strategy strategy
    );
  
  static _TAO_InputMgrIdl_Strategized_Proxy_Broker *
  the_TAO_InputMgrIdl_Strategized_Proxy_Broker (void);
};

//
//            End Strategized Proxy Broker Declaration 
///////////////////////////////////////////////////////////////////////



// TAO_IDL - Generated from 
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/direct_proxy_impl_sh.cpp:31

///////////////////////////////////////////////////////////////////////
//                    Direct  Impl. Declaration
//

class  _TAO_InputMgrIdl_Direct_Proxy_Impl
  : public virtual ::_TAO_ScsProcessIdl_Direct_Proxy_Impl
{
public:
  virtual ~_TAO_InputMgrIdl_Direct_Proxy_Impl (void);
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  InputMgr_failOver (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  InputMgr_switchOver (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  readSnapshot (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  standbyEnvironmentUp (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  updateTime (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  printMsgOn (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  printMsgOff (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/proxy_impl_xh.cpp:24
  
  static void
  dump (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2223
  
  static void
  scs_implementation (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2223
  
  static void
  scs_host (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:2223
  
  static void
  isAlive (
    TAO_Abstract_ServantBase *servant, TAO::Argument **args, int num_args);
  
};

//
//                Direct  Proxy Impl. Declaration
///////////////////////////////////////////////////////////////////////



// TAO_IDL - Generated from 
// be\be_codegen.cpp:1290

#include "inputmgr_skel_tie.hh"

#if defined (__ACE_INLINE__)
#include "inputmgr_skel.inl"
#endif /* defined INLINE */

#endif /* ifndef */

