// ################################################################################
// #
// # File:        G:/bin/p530/src/scs/idl\scsredtype_types.hh (the SOAP types file)
// # Description: Generates typedefs for out parameters to comply with CORBA2.3 spec.
// #
// # This file has been generated by the SOAP generator on 06 Jun 2016.
// # Do not delete it or edit it since changes will be 
// # lost when next generation happens.
// #
// ################################################################################

