//-*-C++-*-
/******************************************************************************/
/*                                                                            */
/*  FILE             : inputmgrbind.idl                                       */
/*  FULL NAME                :                                                */
/*----------------------------------------------------------------------------*/
/*  AUTHOR           : Y. Lozinguez                                           */
/*  COMPANY          : SYSECA                                                 */
/*  CREATION DATE    : Thu Sep  3 16:22:48 1998                               */
/*  LANGUAGE         : C++                                                    */
/*............................................................................*/
/*  OVERVIEW                                                                  */
/*                                                                            */
/*............................................................................*/
/*  CONTENTS                                                                  */
/*                                                                            */
/******************************************************************************/
// IDENTIFICATION:
// $Id: inputmgrbind.idl,v 1.4 1999/08/17 12:06:57 scadaref Exp $
//
// HISTORY:
// $Log: inputmgrbind.idl,v $
// Revision 1.4  1999/08/17 12:06:57  scadaref
// Port on Orbix 3.0
//
// Revision 1.3  1998/12/14 14:13:15  ylo
// Add timekeeper interface.
//
// Revision 1.2  1998/09/11 14:41:18  ylo
// Add DacServer request to inputmgr idl.
//
// Revision 1.1  1998/09/03 14:23:00  ylo
// Initial revision
//


#include <scsprocess.idl>
#include <scsredtype.idl>

interface InputMgrBindingsIdl: ScsProcessIdl
{
  // Binding request
  ScsStatusIdl tryBind(in string serverName, 
                       in string objectName, 
                       out ScsProcessIdl destination,
                       out ScsProcessIdl imgModule);
                       
  ScsStatusIdl getInputMgrObject(out ScsProcessIdl server);

  // Bench
  oneway void printBenchResults();
};
