// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p10 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be\be_codegen.cpp:135

#ifndef _TAO_IDL_FT_FAULTDETECTORFACTORYC_H_
#define _TAO_IDL_FT_FAULTDETECTORFACTORYC_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "orbsvcs/FaultTolerance/fault_tol_export.h"
#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "orbsvcs/FT_CORBAC.h"
#include "orbsvcs/PortableGroupC.h"
#include "orbsvcs/FT_ReplicaC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO TAO_FT_Export

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from 
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_root/root_ch.cpp:62

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_module/module_ch.cpp:49

namespace FT
{
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_FAULT_MONITORING_INTERVAL = "MonitoringInterval";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_NOTIFIER = "Notifier";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_MONITORABLE = "Monitorable";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_EVENT_TYPE_DOMAIN = "FT_CORBA";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_EVENT_TYPE_NAME = "ObjectCrashFault";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_DOMAIN_ID = "FTDomainId";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_LOCATION = "Location";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_TYPE_ID = "TypeId";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FT_GROUP_ID = "GroupId";
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_constant/constant_ch.cpp:52
  
  const char *const FAULT_DETECTOR_ROLE_NAME = "FT_FaultDetector";
  
  // TAO_IDL - Generated from
  // be\be_interface.cpp:644

#if !defined (_FT_FAULTDETECTORFACTORY__VAR_OUT_CH_)
#define _FT_FAULTDETECTORFACTORY__VAR_OUT_CH_
  
  class FaultDetectorFactory;
  typedef FaultDetectorFactory *FaultDetectorFactory_ptr;
  
  typedef
    TAO_Objref_Var_T<
        FaultDetectorFactory
      >
    FaultDetectorFactory_var;
  
  typedef
    TAO_Objref_Out_T<
        FaultDetectorFactory
      >
    FaultDetectorFactory_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:54

#if !defined (_FT_FAULTDETECTORFACTORY_CH_)
#define _FT_FAULTDETECTORFACTORY_CH_
  
  class TAO_FT_Export FaultDetectorFactory
    : public virtual ::PortableGroup::GenericFactory,
      public virtual ::FT::PullMonitorable
  {
  public:
    friend class TAO::Narrow_Utils<FaultDetectorFactory>;
    typedef FaultDetectorFactory_ptr _ptr_type;
    typedef FaultDetectorFactory_var _var_type;
    typedef FaultDetectorFactory_out _out_type;
    
    // The static operations.
    static FaultDetectorFactory_ptr _duplicate (FaultDetectorFactory_ptr obj);
    
    static void _tao_release (FaultDetectorFactory_ptr obj);
    
    static FaultDetectorFactory_ptr _narrow (::CORBA::Object_ptr obj);
    static FaultDetectorFactory_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static FaultDetectorFactory_ptr _nil (void)
    {
      return static_cast<FaultDetectorFactory_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
    
    virtual void change_properties (
        const ::PortableGroup::Properties & property_set);
    
    // TAO_IDL - Generated from
    // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_operation/operation_ch.cpp:46
    
    virtual void shutdown (
        void);
    
    // TAO_IDL - Generated from
    // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_FaultDetectorFactory_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    FaultDetectorFactory (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void FT_FaultDetectorFactory_setup_collocation (void);
    
    // Concrete non-local interface only.
    FaultDetectorFactory (
        ::IOP::IOR *ior,
        TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    FaultDetectorFactory (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~FaultDetectorFactory (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    FaultDetectorFactory (const FaultDetectorFactory &);
    
    void operator= (const FaultDetectorFactory &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_typecode/typecode_decl.cpp:49
  
  extern TAO_FT_Export ::CORBA::TypeCode_ptr const _tc_FaultDetectorFactory;

// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_module/module_ch.cpp:78

} // module FT

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_root/root.cpp:139

extern TAO_FT_Export
TAO::Collocation_Proxy_Broker *
(*FT__TAO_FaultDetectorFactory_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be\be_visitor_traits.cpp:64


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_FT_FAULTDETECTORFACTORY__TRAITS_)
#define _FT_FAULTDETECTORFACTORY__TRAITS_
  
  template<>
  struct TAO_FT_Export Objref_Traits< ::FT::FaultDetectorFactory>
  {
    static ::FT::FaultDetectorFactory_ptr duplicate (
        ::FT::FaultDetectorFactory_ptr p
      );
    static void release (
        ::FT::FaultDetectorFactory_ptr p
      );
    static ::FT::FaultDetectorFactory_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::FT::FaultDetectorFactory_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace FT
{
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultDetectorFactory_ptr); // copying
  TAO_FT_Export void operator<<= ( ::CORBA::Any &, FaultDetectorFactory_ptr *); // non-copying
  TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FaultDetectorFactory_ptr &);
}

#else



TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultDetectorFactory_ptr); // copying
TAO_FT_Export void operator<<= (::CORBA::Any &, FT::FaultDetectorFactory_ptr *); // non-copying
TAO_FT_Export ::CORBA::Boolean operator>>= (const ::CORBA::Any &, FT::FaultDetectorFactory_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




#endif

// TAO_IDL - Generated from
// d:\softs\ace_wrappers_vc10\tao\tao_idl\be\be_visitor_interface/cdr_op_ch.cpp:55


TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

TAO_FT_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const FT::FaultDetectorFactory_ptr );
TAO_FT_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, FT::FaultDetectorFactory_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// be\be_codegen.cpp:1228


TAO_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "FT_FaultDetectorFactoryC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */


