# $Id: Makefile,v 1.1 1999/12/14 14:10:41 jpu Exp $
# $Log: Makefile,v $
# Revision 1.1  1999/12/14 14:10:41  jpu
# Initial revision
#
# Revision 1.1  1999/12/13 13:12:05  scadaref
# Initial revision
#
# Revision 1.1  1999/12/13 13:10:49  scadaref
# Initial revision
#
# Revision 1.1  1999/03/01 13:48:30  scadaref
# Initial revision
#
# Revision 1.1  1999/03/01 13:42:15  scadaref
# Initial revision
#
# Revision 1.1  1997/10/27 18:49:08  scadaref
# Initial revision
#

include $(ROOTDIR)/config.mak
include $(CONFDIR)/stdrules.mak
