# $Id: Makefile,v 1.2 1999/11/17 13:49:33 scadaref Exp $
# $Log: Makefile,v $
# Revision 1.2  1999/11/17 13:49:33  scadaref
# *** empty log message ***
#
# Revision 1.2  1999/11/17 13:48:11  scadaref
# *** empty log message ***
#
# Revision 1.2  1999/11/17 13:47:00  scadaref
# *** empty log message ***
#
# Revision 1.2  1999/11/17 13:38:55  scadaref
# EB
#
# Revision 1.1  1999/03/01 13:48:30  scadaref
# Initial revision
#
# Revision 1.1  1999/03/01 13:42:15  scadaref
# Initial revision
#
# Revision 1.1  1997/10/27 18:49:08  scadaref
# Initial revision
#

include $(ROOTDIR)/config.mak
include $(CONFDIR)/stdrules.mak
