
// -*- C++ -*-
// $Id: Version.h 1807 2011-02-18 17:17:40Z taoadmin $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 6
#define ACE_BETA_VERSION 7
#define ACE_VERSION "5.6a_p10"
#define ACE_OCI_PATCHLEVEL 10
#define ACE_OCI_REV a
