# $Id: Makefile,v 1.1 1999/12/13 13:39:41 scadaref Exp $
# $Log: Makefile,v $
# Revision 1.1  1999/12/13 13:39:41  scadaref
# Initial revision
#
# Revision 1.2  1999/11/17 13:43:53  scadaref
# *** empty log message ***
#
# Revision 1.2  1999/11/17 13:43:16  scadaref
# *** empty log message ***
#
# Revision 1.2  1999/11/17 13:39:40  scadaref
# EB.
#
# Revision 1.1  1999/03/01 13:48:30  scadaref
# Initial revision
#
# Revision 1.1  1999/03/01 13:42:15  scadaref
# Initial revision
#
# Revision 1.1  1997/10/27 18:49:08  scadaref
# Initial revision
#

include $(ROOTDIR)/config.mak
include $(CONFDIR)/stdrules.mak
